### ISSUE TITLE
Project Idea Implementation in  C++11-14

### ISSUE THREAD

**Issue by Ank1taS** [Blaze-Stars/Image-Filter-Beta#2]

**Comment by Himanshu40** [comment]
#14 added

**Comment by Himanshu40** [comment]
Convert Helpers.h to C++ @HembramBeta777 @Tushar7-coder

**Comment by Himanshu40** [comment]
> Convert Helpers.h to C++ @HembramBeta777 @Tushar7-coder

Since this needs evaluation of `filter.c` so that `helpers.h` can be created. Need help to change filters.c to `filters.cpp`. This file needs to adapt C++11-14 requisites.

**Comment by Himanshu40** [comment]
> > Convert Helpers.h to C++ @HembramBeta777 @Tushar7-coder
> 
> Since this needs evaluation of `filter.c` so that `helpers.h` can be created. Need help to change filters.c to `filters.cpp`. This file needs to adapt C++11-14 requisites.

Need help from @Ank1taS, @sabyasachi07, @Tushar7-coder, @HembramBeta777.

**Comment by Himanshu40** [comment]
Discussions regarding filters and bitmaps have been done. MILESTONE 1 is complete.
