### ISSUE TITLE
MILESTONE 1: Project Discussion and Analysis

### ISSUE THREAD

**Issue by Himanshu40** [Blaze-Stars/Image-Filter-Beta#28]
- [x] BITMAPS: #19

FILTERS:

- [x] Reflection: #26
- [x] Gray-Scale: #25
- [x] Sepia: #27
- [x] Blur: #24
- [x] Edges #29

**Comment by Ank1taS** [comment]
Discussion completed for reflection filter #26  and Grayscale filter #25

**Comment by Himanshu40** [comment]
Discussion completed for

- About Bitmaps #19

**Comment by chandrakant100** [comment]
Discussion for
+ About `BITMAPFILEHEADER` #37 
+ About `BITMAPINFOFILEHEADER` #36
